# Generated by Django 3.1.3 on 2020-11-25 11:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201125_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pnone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254700304978', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
