# Generated by Django 3.1.3 on 2020-11-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_pnone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pnone_number',
            new_name='phone_number',
        ),
    ]
